### ISSUE TITLE
Integration testing

### ISSUE THREAD

**Issue by impalah** [press-any-key-tech/web-api-template#46]
Use test containers or similar

```
name: Integration Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.3
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    # 1. Check out the code
    - name: Check out repository
      uses: actions/checkout@v2

    # 2. Set up Python (si usas Python)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # 3. Instalar dependencias
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # 4. Esperar a que el contenedor de PostgreSQL esté listo
    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h 127.0.0.1 -p 5432 -U testuser; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 5
        done

    # 5. Ejecutar las pruebas de integración
    - name: Run integration tests
      env:
        DATABASE_URL: postgres://testuser:testpassword@127.0.0.1:5432/testdb
      run: |
        pytest tests/integration

```
